spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  server:
    port: 8083
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    open-in-view: true
---
sql:
  saveall:
    "INSERT INTO AUDIT_LOG (id, state, type, host, timestamp) VALUES (:id, :state, :type, :host, :timestamp)"  